name: trip_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State management
  provider: ^6.1.1
  # UI components
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  flutter_carousel_widget: ^2.2.0
  # Utils
  intl: ^0.18.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 